### ISSUE TITLE
发现两个小问题

### ISSUE THREAD

**Issue by Feliks151450** [LLM-Red-Team/glm-free-api#1]
1. 不能自动清理会话信息
2. 触发执行代码时，代码和画的图都看不到 （比如“用Python画一朵花”）

**Comment by Vinlic** [comment]
@Feliks151450 最新版本0.0.7，已经修复这两个问题。

**Comment by Feliks151450** [comment]
> @Feliks151450 最新版本0.0.7，已经修复这两个问题。
太强了，坐等docker镜像更新

**Comment by Vinlic** [comment]
@Feliks151450 镜像已经更新了，测试通过。
<img width="819" alt="image" src="https://github.com/LLM-Red-Team/glm-free-api/assets/20235341/c51d3f0a-bddd-4120-82f4-8ce30b7fe22f">
