### ISSUE TITLE
文本提问被理解为绘画指令

### ISSUE THREAD

**Issue by manjieqi** [LLM-Red-Team/glm-free-api#12]
当输入提示词“你有多少种绘画风格”时，API应该返回一个关于绘画风格种类的信息，但实际上API却错误地将其解释为一个绘画指令，并尝试根据这个指令绘制一幅图像。

### **glm-free-api：**
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/40858189/bc5e6b9a-6c59-4bcc-b2ac-b6510e757c32)

### **官网：**
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/40858189/eed6c851-37a3-414e-9eea-4fb9db20655b)

**Comment by Vinlic** [comment]
传入图像官网版本也是会直接进行解析，这个是一致的。
是否绘图取决于上下文是否让模型调起绘图tool，如果前文进行绘图那么大概率后续会继续绘图。

**Comment by manjieqi** [comment]
> 传入图像官网版本也是会直接进行解析，这个是一致的。
> 是否绘图取决于上下文是否让模型调起绘图tool，如果前文进行绘图那么大概率后续会继续绘图。

但是我看log里面是作为文件解析的，它在读文件

上面两张图的提示词一样的，还有就是客户端新开对话页面也会合并前文吗，这才是指令错误的原因吗？

**Comment by Vinlic** [comment]
这是正确的，任何图像的读取本质上就是上传文件并解析，只是你所使用的前端框架和free api没有将这个过程透明化，当你传入图像并发出消息时：前端框架将图像编码为base64比以gpt4v格式发送消息->free-api接收图像并上传到GLM平台->将图像引用和提问消息发给GLM解答。

新开对话是新的上下文，对话合并是被迫的选择，因为几乎所有平台网页接口单次仅支持传送一条消息。

**Comment by manjieqi** [comment]
![S40413-00251583_com.quark.browser.png](https://github.com/LLM-Red-Team/glm-free-api/assets/40858189/24d83e88-392c-4ba0-982c-a265fd9aadcb)

图片那个可能是客户端的问题

但是就用仓库提供dify，新开对话，还是不对啊

**Comment by Vinlic** [comment]
你可以copy日志中对话合并的内容到官网来验证效果，我们无法控制绘图工具是否调用

**Comment by Vinlic** [comment]
![Screenshot_2024-04-13-00-32-37-451_com zhipuai qingyan](https://github.com/LLM-Red-Team/glm-free-api/assets/20235341/5b943f1c-4812-4763-bd84-498aaabd84df)
如图所示复现该问题，对话合并指令是不可更改的

**Comment by manjieqi** [comment]
哦哦，意思是对话合并导致了glm误判，错误调用了工具，明白了。感觉不太智能啊，那官网怎么合并对话的

**Comment by Vinlic** [comment]
glm绘图tool的触发条件比较敏感，许多提示词都可能引发绘图，你可以尝试不使用这种prompt
![Screenshot_2024-04-13-00-38-23-843_com zhipuai qingyan](https://github.com/LLM-Red-Team/glm-free-api/assets/20235341/f03fc9e8-1253-4c69-be9f-d7b16c6989bd)

**Comment by Vinlic** [comment]
官网ChatGLM4合并对话的special_token是不开源的，而我们合并所使用的special_token取自开源的ChatGLM3，这个已经是目前隔离消息效果最好的一个。

**Comment by manjieqi** [comment]
OK，感谢解答
