### ISSUE TITLE
求助大佬，如何部署在hugging face的space中

### ISSUE THREAD

**Issue by Geek66666** [LLM-Red-Team/glm-free-api#13]
rt

**Comment by Vinlic** [comment]
如果支持容器部署，都是可以的。

**Comment by Geek66666** [comment]
导入了dockerfile但是部署失败了QAQ

**Comment by Vinlic** [comment]
@Geek66666 需要提供错误截图确认

**Comment by Geek66666** [comment]
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/61675035/9f5e03c0-74fb-4f72-b143-524c457ab7c3)
就是这样了，小白没学过docker之类的。。。
