### ISSUE TITLE
token统计建议

### ISSUE THREAD

**Issue by zmlstc** [LLM-Red-Team/glm-free-api#14]
token统计建议可以采用开源的token计算器，比如openai的tiktoken：https://github.com/openai/tiktoken
或者设置一个固定的比例，比如中文字数/1.6。会比现在写一个固定数值好一些。

**Comment by Vinlic** [comment]
@zmlstc 统计一个并非准确的token数并没有实际意义，运行tiktoken是多余的性能消耗，我们倾向于更低的资源消耗。
