### ISSUE TITLE
能否增加image接口？

### ISSUE THREAD

**Issue by lfglfg11** [LLM-Red-Team/glm-free-api#2]
希望增加兼容openai调用dalle3的/v1/images/generations接口

**Comment by Vinlic** [comment]
@lfglfg11 最近应该会支持，请持续关注。

**Comment by Vinlic** [comment]
@lfglfg11 @kokojacket  最新0.0.12版本，已[支持兼容dalle3绘图调用接口](https://github.com/LLM-Red-Team/glm-free-api/commit/ea49bd3023c2c63209eb32c55a45bb64f2a22191)
