### ISSUE TITLE
有没有lobe-chat这类客户端的具体接入教程

### ISSUE THREAD

**Issue by liuzj288** [LLM-Red-Team/glm-free-api#23]

**Comment by a5412398** [comment]
不需要教程吧？部署了之后直接填内容就行了。。你说的是部署lebe的教程吗？

**Comment by liuzj288** [comment]
> 不需要教程吧？部署了之后直接填内容就行了。。你说的是部署lebe的教程吗？

但是占用openai接口不就不能用官方的了？

**Comment by a5412398** [comment]
> > 不需要教程吧？部署了之后直接填内容就行了。。你说的是部署lebe的教程吗？
> 
> 但是占用openai接口不就不能用官方的了？
> 

的确是这样的，没办法，我是部署了这个之后拿来给小爱音箱用的。
