### ISSUE TITLE
接入gpt_academic使用时，遇到SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by wwjCMP** [LLM-Red-Team/glm-free-api#25]
https://github.com/binary-husky/gpt_academic/issues/1783
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.101.5', port=8006): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))

**Comment by Vinlic** [comment]
你的协议可能使用了https，请改为http。

**Comment by wwjCMP** [comment]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.101.5', port=8006): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94682f7d10>: Failed to establish a new connection: [Errno 113] No route to host')) 改为之后变下面这个报错了

**Comment by wwjCMP** [comment]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

**Comment by Vinlic** [comment]
很明显请求地址是openai的地址，不是free api

**Comment by wwjCMP** [comment]
现在可以了
