### ISSUE TITLE
[FR] 多服务同时请求应对机制

### ISSUE THREAD

**Issue by wwjCMP** [LLM-Red-Team/glm-free-api#26]
1|glm-free-api  | [2024-05-14 23:41:51.415][error][chat.ts<327,14>] Invalid response Content-Type: application/json
1|glm-free-api  | [2024-05-14 23:41:51.416][info][server.ts<66,36>] <- POST /v1/chat/completions 131ms
1|glm-free-api  | [2024-05-14 23:41:51.417][error][chat.ts<331,47>] {"message":"当前还有其他请求正在进行","result":[],"status":10006}
1|glm-free-api  |
1|glm-free-api  | [2024-05-14 23:41:51.541][error][chat.ts<327,14>] Invalid response Content-Type: application/json
1|glm-free-api  | [2024-05-14 23:41:51.542][info][server.ts<66,36>] <- POST /v1/chat/completions 175ms
1|glm-free-api  | [2024-05-14 23:41:51.543][error][chat.ts<331,47>] {"message":"当前还有其他请求正在进行","result":[],"status":10006}
1|glm-free-api  |
1|glm-free-api  | [2024-05-14 23:42:16.377][success][chat.ts<358,14>] Stream has completed transfer 25378ms

像gpt_academic有些任务会同时申请多个请求，能不能通过某些机制延迟响应，而不至于终止请求？

**Comment by Vinlic** [comment]
目前内部会自动重试3次，每次间隔5s，建议使用更多账号提高并发，或者降低你的并发量

**Comment by wwjCMP** [comment]
多个账号的话，直接将api_key写成 TOKEN1,TOKEN2,TOKEN3 这就行了嘛？

**Comment by Vinlic** [comment]
是的
