### ISSUE TITLE
似乎EN版没有chatglm_refresh_token

### ISSUE THREAD

**Issue by Morris-Lucifer** [LLM-Red-Team/glm-free-api#30]
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/54257509/5745f45d-de46-47ac-9205-97c7f611337e)

**Comment by Vinlic** [comment]
目前未遇到出问题，请确保您已登录。

**Comment by Morris-Lucifer** [comment]
> 目前未遇到出问题，请确保您已登录。

登录了，网页上能正常对话，cookie刷新了几次都没看到，edge浏览器

**Comment by Vinlic** [comment]
尝试更换浏览器重试登录，或切换到其它网络线路测试？

**Comment by Vinlic** [comment]
那可能需要更换到国内线路了，我们测试每次登录都能获得refresh token。

**Comment by Morris-Lucifer** [comment]
> 那可能需要更换到国内线路了，我们测试每次登录都能获得refresh token。
应该是的，试了下Chrome也没有refresh token，+86只有一个chatglm_token_expires
