### ISSUE TITLE
[FR] Token 写到一个文件中被读取

### ISSUE THREAD

**Issue by wwjCMP** [LLM-Red-Team/glm-free-api#31]
有一些软件会对API的格式进行限制。
本代理直接从在某个本地文件中读取获得的token，然后软件那边使用格式和openai兼容的伪API来调用。

**Comment by Vinlic** [comment]
几乎所有软件都能通过API KEY形式传送TOKEN，我们不希望在本地增加额外的配置流程。

**Comment by wwjCMP** [comment]
是可以，只不过有些会对API格式做严格的限制

**Comment by wwjCMP** [comment]
如果是jws格式，首先它就识别为API格式错误

**Comment by Vinlic** [comment]
可以提供软件的名称吗

**Comment by wwjCMP** [comment]
cursor

**Comment by Vinlic** [comment]
能否提供报错信息或截图呢

**Comment by wwjCMP** [comment]
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/32979859/e9135f19-8e84-4ded-84fa-0ce9fdabbe27)

**Comment by wwjCMP** [comment]
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/32979859/671cfd90-40ce-4654-9152-49da78e126b4)

**Comment by Vinlic** [comment]
如果它仅支持openai的key，那也许应该通过one-api中转
