### ISSUE TITLE
可以具体解释一下怎么上传文件吗？

### ISSUE THREAD

**Issue by H-XZ** [LLM-Red-Team/glm-free-api#32]
示例里通过网络地址发送了文档，使用时可以通过什么方式使其读取本地文档，图片之类的文件吗？

**Comment by Vinlic** [comment]
可以将文件编码为base64字符串，通过image_url或者file_url去传送，和网络地址传送方法一样
需要注意base64需要添加头部（比如PNG图像）：data:image/png;base64,
