### ISSUE TITLE
图像生成的接口好像不行了

### ISSUE THREAD

**Issue by GriMu** [LLM-Red-Team/glm-free-api#34]
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/38001542/4d098104-8aba-49f7-9b82-41163765227e)
和之前一样传，一直生成失败

**Comment by GriMu** [comment]
看了下应该是api返回结构改了，把content里面的status拿到外面了，自己改下就行
![image](https://github.com/LLM-Red-Team/glm-free-api/assets/38001542/6c525957-6021-4c7b-a3a6-4b6c8d34f7d5)

**Comment by Vinlic** [comment]
0.0.31已经跟进修复
