### ISSUE TITLE
<|sytstem|> 

### ISSUE THREAD

**Issue by abincn** [LLM-Red-Team/glm-free-api#37]
\src\api\controllers\chat.ts(549): 
       const role = message.role
          .replace("system", "<|sytstem|>")
          .replace("assistant", "<|assistant|>")
          .replace("user", "<|user|>");

对话中会把  <|sytstem|>  当成对话内容。

**Comment by Vinlic** [comment]
减少使用system消息，这个是为了实现合并上下文的对话间隔离的special token，如果发生幻觉有几率会复述出来，你可以把设定放到user消息上，另外要彻底避免也可以考虑使用原生的多轮对话功能，具体看文档
