### ISSUE TITLE
支持清影

### ISSUE THREAD

**Issue by acleverfreebird** [LLM-Red-Team/glm-free-api#40]
智谱的制作视频AI模型出了！
大佬能帮帮逆向一下吗？

**Comment by Vinlic** [comment]
已经支持了，请见文档。

**Comment by goxofy** [comment]
@Vinlic 貌似智谱那边调整了，现在清影会报错 Video generation error: extract_area: bad extract area

**Comment by Vinlic** [comment]
未复现问题，检查你的传参
@goxofy
