### ISSUE TITLE
如何修改默认端口号？

### ISSUE THREAD

**Issue by zengyunda** [LLM-Red-Team/glm-free-api#7]
想把大佬的多个项目部署在本地，但是几个项目均是使用8000的端口号，请大佬怎么修改端口号呢？

**Comment by Vinlic** [comment]
@zengyunda 
使用docker的话修改启动参数即可 -p xxxx:8000
使用原生部署的话，可以修改configs/dev/service.yml，或者启动时指定pm2 start dist/index.js --name "glm-free-api" -- --port xxxx

**Comment by zengyunda** [comment]
好嘞，感谢大佬回复~
